[build]
  command = "npm run build && npm run algolia"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"

[[redirects]]
  from = "https://www.samoyedhealthfoundation.com/*"
  to = "https://www.samoyedhealthfoundation.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://samoyedhealthfoundation.com/*"
  to = "https://www.samoyedhealthfoundation.org/:splat"
  status = 301
  force = true
