baseurl = "/"
title = "SCARF"
languageLang = "en"
theme = "hugo-universal-theme"
themesDir = "./themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Newlines between headers - ./content/about/past-sponsored-events.md
      # Images with links and custom dimensions: ./content/blog/akc-chf-25th-anniversary-contributor.md
      unsafe = true

[menu]

# Main menu

# About
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 2

# Owners
[[menu.main]]
  identifier = "owners"
  name = "Owners"
  url = "/owners"
  weight = 3

# Breeders
[[menu.main]]
  identifier = "breeders"
  name = "Breeders"
  url = "/breeders"
  weight = 4

# Research
[[menu.main]]
  identifier = "research"
  name = "Research"
  url = "/research"
  weight = 5

# Diseases
[[menu.main]]
  identifier = "diseases"
  name = "Diseases"
  url  = "/diseases"
  weight = 6

# Databases
[[menu.main]]
  identifier = "databases"
  name = "Databases"
  url = "/databases"
  weight = 7

# Blog
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url  = "/blog/"
  weight = 8

# Top bar social links menu

# [[menu.topbar]]
#   weight = 1
#   name = "Facebook"
#   url = "https://www.facebook.com/samoyed.foundation/"
#   pre = "<i class='fab fa-2x fa-facebook'></i>"

[params]
  viewMorePostLink = "/blog/"
  author = "Matt Odille"
  defaultKeywords = ["samoyed", "scarf", "sca"]
  mainSections = ["blog"]
  defaultDescription = "Samoyed Club of America Education and Research Foundation"

  # Social media
  facebook_site = "https://www.facebook.com/samoyed.foundation/" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
  twitter_site = "" # the Twitter handle of your site (without the '@')
  default_sharing_image = "img/og-image.png"

  # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
  enableGoogleMaps = false
  googleMapsApiKey = ""

  latitude  = "30.4739452"
  longitude = "-90.1081459"

  # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
  style = "violet"

  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 50 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - register your account to https://formspree.io/register
  # - login and create new form
  # - set your form's endpoint url under 'formspree_action' below
  # - upload the generated site to your server
  # - test a dummy email yourself
  # - you're done. Happy mailing!
  #
  # Enable the contact form by entering your Formspree.io endpoint url
  formspree_action = ""
  contact_form_ajax = false

  about_us = "<p>We're an organization devoted to improving the health of the Samoyed breed.</p>"
  copyright = "Copyright &copy; 2021, Samoyed Club of America Education and Research Foundation, Inc."

  # Format dates with Go's time formatting
  date_format = "January 2, 2006"

  logo = "img/logo.png"
  logo_small = "img/logo-small.png"
  address = """<p>
      <a href="https://www.facebook.com/samoyed.foundation">
        <i class='fab fa-2x fa-facebook'></i>
      </a>
      <a href="mailto:president@samoyedhealthfoundation.org">
        <i class='fas fa-2x fa-envelope'></i>
      </a>
    </p>
    """

[Permalinks]
  blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
  enable = true
  text = """
         <i class="fas fa-bullhorn"></i>
         <span>Follow our <a style="color: #fff; background-color: #4460ae; text-decoration: underline;" target="_blank" href="https://www.facebook.com/samoyed.foundation">Facebook page</a> for updates!</span>
         """

# Enable and disable widgets for the right sidebar
[params.widgets]
  categories = true
  tags = true
  search = true

[params.carousel]
  enable = true
  # All carousel items are defined in their own files. You can find example items
  # at 'exampleSite/data/carousel'.
  # For more informtion take a look at the README.

[params.features]
  enable = true
  # All features are defined in their own files. You can find example items
  # at 'exampleSite/data/features'.
  # For more informtion take a look at the README.

[params.testimonials]
  enable = false
  # All testimonials are defined in their own files. You can find example items
  # at 'exampleSite/data/testimonials'.
  # For more informtion take a look at the README.
  title = "Testimonials"
  subtitle = ""

[params.see_more]
  enable = true
  icon = "fa fa-question"
  title = "Do you want to help?"
  subtitle = "You can contribute by donating, volunteering, or enrolling your Samoyed in the DNA Database (it's easier than it sounds!)"
  link_url = "/how-you-can-help"
  link_text = "Learn More"

[params.clients]
  enable = false
  # All clients are defined in their own files. You can find example items
  # at 'exampleSite/data/clients'.
  # For more informtion take a look at the README.
  title = "Our Clients"
  subtitle = ""

[params.recent_posts]
  enable = true
  title = "From our blog"
  subtitle = ""

# Search via Algolia

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "description", "summary", "date", "publishdate", "permalink"]
params = ["categories", "tags"]

[outputs]
home = ["HTML", "RSS", "Algolia"]
