backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# https://www.netlifycms.org/docs/configuration-options/#publish-mode
# Adds an interface for drafting, reviewing, and approving posts
publish_mode: editorial_workflow

media_folder: "site/static/img/uploads" # Location for uploaded media files
public_folder: "/img/uploads" # What to begin the src attribute for uploaded media with

display_url: "https://www.samoyedhealthfoundation.org"
logo_url: "https://www.samoyedhealthfoundation.org/img/logo.png"

collections:
  - name: "general" # Used in routes, e.g., /admin/collections/blog
    label: "General Pages" # Used in the UI
    label_singular: "General Page"
    files:
      - name: "become-a-health-information-liaison"
        label: "Become a Liason"
        file: "site/content/become-a-health-information-liaison.md" # The path to the file
        extension: "md"
        slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        editor:
          preview: false
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "become-a-health-information-reviewer"
        label: "Become a Reviewer"
        file: "site/content/become-a-health-information-reviewer.md" # The path to the file
        extension: "md"
        slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        editor:
          preview: false
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "contact"
        label: "Contact"
        file: "site/content/contact.md" # The path to the file
        extension: "md"
        slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        editor:
          preview: false
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "dog-food-recall-information"
        label: "Dog Food Recall Information"
        file: "site/content/dog-food-recall-information.md" # The path to the file
        extension: "md"
        slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        editor:
          preview: false
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "how-you-can-help"
        label: "How You Can Help"
        file: "site/content/how-you-can-help.md" # The path to the file
        extension: "md"
        slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        editor:
          preview: false
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - name: "optigen-dna-test-for-retinal-dysplasia-dwarfism-in-the-samoyed"
        label: "Optigen DNA test for Retinal Dysplasia/Dwarfism in the Samoyed"
        file: "site/content/optigen-dna-test-for-retinal-dysplasia-dwarfism-in-the-samoyed.md" # The path to the file
        extension: "md"
        slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        editor:
          preview: false
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About Pages" # Used in the UI
    label_singular: "About Page"
    folder: "site/content/about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    label_singular: "Blog Post"
    folder: "site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Featured Image", name: "banner", widget: "image"}
      - {label: "Categories", name: "categories", widget: "select", multiple: true, options: ["articles", "events"]}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["history", "pdf"]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "breeders" # Used in routes, e.g., /admin/collections/blog
    label: "Breeders Pages" # Used in the UI
    label_singular: "Breeders Page"
    folder: "site/content/breeders" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "databases" # Used in routes, e.g., /admin/collections/blog
    label: "Databases Pages" # Used in the UI
    label_singular: "Databases Page"
    folder: "site/content/databases" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "diseases" # Used in routes, e.g., /admin/collections/blog
    label: "Diseases" # Used in the UI
    label_singular: "Disease"
    folder: "site/content/diseases" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "owners" # Used in routes, e.g., /admin/collections/blog
    label: "Owners Pages" # Used in the UI
    label_singular: "Owners Page"
    folder: "site/content/owners" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "research" # Used in routes, e.g., /admin/collections/blog
    label: "Research Pages" # Used in the UI
    label_singular: "Research Page"
    folder: "site/content/research" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "research-collections" # Used in routes, e.g., /admin/collections/blog
    label: "Research Collections" # Used in the UI
    label_singular: "Research Collection"
    folder: "site/content/research/research-study-collection-clinics" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "research-studies" # Used in routes, e.g., /admin/collections/blog
    label: "Research Studies" # Used in the UI
    label_singular: "Research Study"
    folder: "site/content/research/current-studies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "md"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
